### ISSUE TITLE
Switching theme (dark/light) resets

### ISSUE THREAD

**Issue by Pimak** [BLKKKBVSIK/AnimalCrossingCompletionist#1]
Whenever I switch to dark theme or to light theme, the app resets to the beginning, asking for my name and if I bought the game.
However it still keep tracks of the different items I said I already had

**Comment by BLKKKBVSIK** [comment]
Hi @Pimak !
I already saw this issue, it's already patch on my computer, but it ll be patched in the next update probably today or tomorrow on the Play Store

**Comment by BLKKKBVSIK** [comment]
Btw, this issue only occur on the first launch of the app, if you completely close your app and relaunch it, you ll no more have this issue.
It's a quick solution until next update.
